### ISSUE TITLE
BSQL Q27 fails at SF10K on the 17-node cluster ("existing" allocator)

### ISSUE THREAD

**Issue by Christian8491** [rapidsai/tpcx-bb#101]
Looks like the error comes from here
 https://github.com/rapidsai/tpcx-bb/blob/main/tpcx_bb/queries/q27/tpcx_bb_query_27_sql.py#L47

```
Using default arguments
Connected to tcp://172.16.8.158:8786
BlazingContext ready
Encountered Exception while running query
Traceback (most recent call last):
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/utils.py", line 174, in raise_on_meta_error
    yield
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/core.py", line 5144, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "tpcx_bb_query_27_sql.py", line 48, in ner_parser
    nlp = spacy.load("en_core_web_sm")
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 170, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 191, in load_model_from_package
    return cls.load(**overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 239, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 222, in load_model_from_path
    return nlp.from_disk(model_path, exclude=disable)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/language.py", line 974, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 690, in from_disk
    reader(path / key)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/language.py", line 950, in deserialize_vocab
    self.vocab.from_disk(path)
  File "vocab.pyx", line 472, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 432, in spacy.vectors.Vectors.from_disk
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 690, in from_disk
    reader(path / key)
  File "vectors.pyx", line 425, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/cupy/io/npz.py", line 71, in load
    return cupy.array(obj)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/cupy/creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1785, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1862, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1951, in cupy.core.core._send_object_to_gpu
  File "cupy/cuda/stream.pyx", line 267, in cupy.cuda.stream.Stream.record
  File "cupy/cuda/stream.pyx", line 99, in cupy.cuda.stream.Event.__init__
  File "cupy/cuda/runtime.pyx", line 571, in cupy.cuda.runtime.eventCreateWithFlags
  File "cupy/cuda/runtime.pyx", line 574, in cupy.cuda.runtime.eventCreateWithFlags
  File "cupy/cuda/runtime.pyx", line 197, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/xbb_tools/utils.py", line 326, in run_bsql_query
    config=config,
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/xbb_tools/utils.py", line 63, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_27_sql.py", line 88, in main
    ner_parsed = sentences.map_partitions(ner_parser, "sentence")
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/core.py", line 643, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/core.py", line 5194, in map_partitions
    meta = _emulate(func, *args, udf=True, **kwargs)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/core.py", line 5144, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/utils.py", line 195, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `ner_parser`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
CUDARuntimeError('cudaErrorMemoryAllocation: out of memory')

Traceback:
---------
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/utils.py", line 174, in raise_on_meta_error
    yield
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/core.py", line 5144, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "tpcx_bb_query_27_sql.py", line 48, in ner_parser
    nlp = spacy.load("en_core_web_sm")
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 170, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 191, in load_model_from_package
    return cls.load(**overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 239, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 222, in load_model_from_path
    return nlp.from_disk(model_path, exclude=disable)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/language.py", line 974, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 690, in from_disk
    reader(path / key)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/language.py", line 950, in deserialize_vocab
    self.vocab.from_disk(path)
  File "vocab.pyx", line 472, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 432, in spacy.vectors.Vectors.from_disk
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/spacy/util.py", line 690, in from_disk
    reader(path / key)
  File "vectors.pyx", line 425, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/cupy/io/npz.py", line 71, in load
    return cupy.array(obj)
  File "/home/christianc/conda/envs/bsql-tpcx/lib/python3.7/site-packages/cupy/creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1785, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1862, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1951, in cupy.core.core._send_object_to_gpu
  File "cupy/cuda/stream.pyx", line 267, in cupy.cuda.stream.Stream.record
  File "cupy/cuda/stream.pyx", line 99, in cupy.cuda.stream.Event.__init__
  File "cupy/cuda/runtime.pyx", line 571, in cupy.cuda.runtime.eventCreateWithFlags
  File "cupy/cuda/runtime.pyx", line 574, in cupy.cuda.runtime.eventCreateWithFlags
  File "cupy/cuda/runtime.pyx", line 197, in cupy.cuda.runtime.check_status


```

**Comment by beckernick** [comment]
This has been resolved. Closing.
