### ISSUE TITLE
DASK Q05 SF1k Groupby Failing  with list object has no attribute groupby

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/tpcx-bb#128]
Command
```python
python tpcx_bb_query_05.py --config ../../benchmark_runner/benchmark_config.yaml
```
Trace:
```python
Using default arguments
{
  "type": "Scheduler",
  "id": "Scheduler-c21fba8f-8539-41b0-bf54-b427d45b09d7",
  "address": "ucx://10.33.228.70:8786",
  "services": {
    "dashboard": 8787
  },
  "workers": {}
}
Connected!
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_05.py", line 266, in main
    results_dict = client.compute(*ml_tasks, sync=True)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 2930, in compute
    result = self.gather(futures)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/utils.py", line 29, in apply
    return func(*args, **kwargs)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 279, in _groupby_aggregate
    return aggfunc(df.groupby(level=levels, sort=sort, **dropna), **kwargs)
AttributeError: 'list' object has no attribute 'groupby'

```

Env:

```
cudf                      0.17.0a201105   cuda_10.2_py37_g1556a4997c_171    rapidsai-nightly
dask-cudf                 0.17.0a201105   py37_g1556a4997c_171    rapidsai-nightly
libcudf                   0.17.0a201105   cuda10.2_g1556a4997c_171    rapidsai-nightly
(rapids-tpcx-bb) vjawa@exp01:/raid/vjawa/tpcx-bb/tpcx_bb/queries/q05$ conda list | grep dask
dask                      2.30.0+22.g2b45fdb9          pypi_0    pypi
dask-cuda                 0.17.0a201105           py37_30    rapidsai-nightly
dask-cudf                 0.17.0a201105   py37_g1556a4997c_171    rapidsai-nightly
```

**Comment by VibhuJawa** [comment]
Can confirm that #129  was the root cause, closing this issue in favor of that one.
