### ISSUE TITLE
ValueError: Cannot align indices with non-unique values on Query 05

### ISSUE THREAD

**Issue by Jiahong-Nvidia** [rapidsai/tpcx-bb#133]
Running with internal dataset both SF100 and SF1000 with success. But using a self-generated dataset from bigBench dataGen's raw files runs into the following error:

Encountered Exception while running query
Traceback (most recent call last):
  File "/fsx/install/tpcx-bb-nvidia/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/fsx/install/tpcx-bb-nvidia/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q05/tpcx_bb_query_05.py", line 266, in main
    results_dict = client.compute(*ml_tasks, sync=True)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 2930, in compute
    result = self.gather(futures)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/methods.py", line 271, in assign
    df[name] = val
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/dataframe.py", line 750, in __setitem__
    self.insert(len(self._data), arg, value)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/dataframe.py", line 3001, in insert
    self._index, how="right", sort=False
  File "/home/ec2-user/anaconda3/envs/aws-rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/series.py", line 4161, in _align_to_index
    raise ValueError("Cannot align indices with non-unique values")
ValueError: Cannot align indices with non-unique values

More analysis into the dataset found that the new dataset has an extra column of  __null_dask_index__ for the index and 2 num_row_groups instead of 1 in the shared parquet file.

**Comment by beckernick** [comment]
Thanks for filing. Likely due to upstream changes in the parquet writer in between now and when the succeeding dataset were generated.

**Comment by beckernick** [comment]
I can reproduce this error with a fresh clone and environment

**Comment by beckernick** [comment]
This error arises due to the `reset_index(drop=True)` call [here](https://github.com/rapidsai/tpcx-bb/blob/a95bf943b49b172d191b2b442bf345c6b80a8764/tpcx_bb/queries/q05/tpcx_bb_query_05.py#L184). Dask now uses a `__null_dask_index` when the parquet metadata includes it as a placeholder, but it's not playing cleanly with the `setitem` + reset index on the series.

I've just verified that we can safely remove this and still pass correctness checks for this query, so I suspect it only exists due to an old bug we had to work around.
