### ISSUE TITLE
[BUG] Q14 Dask Fails at metadata inference  on `0.15.0a200715's` nightlty

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/tpcx-bb#44]
Q14 Dask Fails at metadata inference  on `0.15.0a200715` nightly

```
Using default arguments
Connected to ucx://172.22.1.26:8786
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/utils.py", line 173, in raise_on_meta_error
    yield
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 4786, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/utils.py", line 1090, in partial_by_order
    return function(*args2, **kwargs)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/series.py", line 1530, in __ge__
    return self._binaryop(other, "ge")
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/series.py", line 1060, in _binaryop
    outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 98, in binary_operator
    lhs=self, rhs=rhs, op=binop, out_dtype=out_dtype, reflect=reflect
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 439, in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
  File "cudf/_lib/binaryop.pyx", line 201, in cudf._lib.binaryop.binaryop
  File "cudf/_lib/binaryop.pyx", line 127, in cudf._lib.binaryop.binaryop_v_s
RuntimeError: CUDA_ERROR_INVALID_PTX

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid/vjawa/tpcxbb_33/vjawa_f_tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 278, in run_dask_cudf_query
    config=config,
  File "/raid/vjawa/tpcxbb_33/vjawa_f_tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 59, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_14.py", line 120, in main
    output_table["am"] = (output_table["t_hour"] >= q14_morning_startHour) & (
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 1482, in <lambda>
    return lambda self, other: elemwise(op, self, other)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 4786, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/utils.py", line 194, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `ge`.

Original error is below:
------------------------
RuntimeError('CUDA_ERROR_INVALID_PTX')

Traceback:
---------
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/utils.py", line 173, in raise_on_meta_error
    yield
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 4786, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/utils.py", line 1090, in partial_by_order
    return function(*args2, **kwargs)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/series.py", line 1530, in __ge__
    return self._binaryop(other, "ge")
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/series.py", line 1060, in _binaryop
    outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 98, in binary_operator
    lhs=self, rhs=rhs, op=binop, out_dtype=out_dtype, reflect=reflect
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/raid/vjawa/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 439, in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
  File "cudf/_lib/binaryop.pyx", line 201, in cudf._lib.binaryop.binaryop
  File "cudf/_lib/binaryop.pyx", line 127, in cudf._lib.binaryop.binaryop_v_s
```

Relevant Libraries:
```
cudf                      0.15.0a200715   py37_g1f4209c3a_2756    rapidsai-nightly
dask-cudf                 0.15.0a200715   py37_g1f4209c3a_2756    rapidsai-nightly
libcudf                   0.15.0a200715   cuda10.2_g1f4209c3a_2756    rapidsai-nightly

(rapids-tpcx-bb) vjawa@exp01:/raid/vjawa/tpcxbb_33/tpcx-bb/tpcx_bb/queries/q14$ conda list | grep dask
dask                      2.20.0+10.g1f57364a          pypi_0    pypi
dask-cuda                 0.15.0a200715           py37_76    rapidsai-nightly
dask-cudf                 0.15.0a200715   py37_g1f4209c3a_2756    rapidsai-nightly

(rapids-tpcx-bb) vjawa@exp01:/raid/vjawa/tpcxbb_33/tpcx-bb/tpcx_bb/queries/q14$ conda list | grep dis
distributed               2.20.0+13.g1936af5e          pypi_0    pypi
```

**Comment by randerzander** [comment]
@VibhuJawa I just tested this on sf1k on the latest nightlies and don't have the issue.

Please re-open if necessary.
