### ISSUE TITLE
[BUG] benchmark_runner.py calls to gc.collect throw "RuntimeError: IOLoop is closed"

### ISSUE THREAD

**Issue by randerzander** [rapidsai/tpcx-bb#52]
Running gc.collect calls on all workers via client.run results in a crash: 
```
Using default arguments
Connected to ucx://172.16.8.240:8786
Pure Dask Queries
01
/home/rgelhausen/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/cudf/core/frame.py:1965: UserWarning: When using a sequence of booleans for `ascending`, `na_position` flag is not yet supported and defaults to treating nulls as greater than all numbers
  "When using a sequence of booleans for `ascending`, "
Traceback (most recent call last):
  File "benchmark_runner.py", line 67, in <module>
    client.run(gc.collect)
  File "/home/rgelhausen/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 2487, in run
    return self.sync(self._run, function, *args, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/rgelhausen/conda/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/utils.py", line 304, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
```

**Comment by VibhuJawa** [comment]
Closed by https://github.com/rapidsai/tpcx-bb/pull/48
