### ISSUE TITLE
Q20 fails during metadata inference for remove_inf_and_nulls

### ISSUE THREAD

**Issue by beckernick** [rapidsai/tpcx-bb#58]
In the 2020-07-27 nightly from ~9 AM EDT, Q20 fails at SF1K during the metadata inference before running `remove_inf_and_nulls`. Something likely changed in cuDF/dask underneath the query.

```
python tpcx_bb_query_20.py --config_file=../../benchmark_runner/benchmark_config.yaml
Using default arguments
Connected to tcp://172.22.1.26:8786
/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask_cudf/core.py:326: UserWarning: Rearranging data by column hash. Divisions will lost. Set ignore_index=False to preserve Index values.
  "Rearranging data by column hash. Divisions will lost. "
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/utils.py", line 174, in raise_on_meta_error
    yield
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5125, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "tpcx_bb_query_20.py", line 101, in remove_inf_and_nulls
    df.fillna(value_dict, inplace=True)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/frame.py", line 1319, in fillna
    copy_data[name] = copy_data[name].fillna(value[name],)
KeyError: 'user_sk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_20.py", line 202, in main
    remove_inf_and_nulls, column_names=ratio_columns, value=0.0
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 642, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5175, in map_partitions
    meta = _emulate(func, *args, udf=True, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5125, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/utils.py", line 195, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `remove_inf_and_nulls`.

You have supplied a custom function and Dask is unable to
determine the type of output that that function returns.

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
KeyError('user_sk')

Traceback:
---------
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/utils.py", line 174, in raise_on_meta_error
    yield
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5125, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "tpcx_bb_query_20.py", line 101, in remove_inf_and_nulls
    df.fillna(value_dict, inplace=True)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/frame.py", line 1319, in fillna
    copy_data[name] = copy_data[name].fillna(value[name],)
```

**Comment by beckernick** [comment]
This does not happen in the 2020-07-24 nightly (with dask/distributed master as of that date), so presumably one of the PRs between then and now

**Comment by beckernick** [comment]
This was introduced in rapidsai/cudf#5727 with the `fillna` refactor. cc @galipremsagar for visibility, but I'll file a raw cuDF issue with a minimal reproducer shortly.

**Comment by beckernick** [comment]
Crosslinking https://github.com/rapidsai/cudf/issues/5772 , as resolving this issue will fix this query without any changes. Will close when it lands.

**Comment by beckernick** [comment]
Resolved by https://github.com/rapidsai/cudf/pull/5568 . Closing
