### ISSUE TITLE
Q28 fails when run from benchmark runner on a single node

### ISSUE THREAD

**Issue by beckernick** [rapidsai/tpcx-bb#59]
Q28 appears to fail when run from the benchmark runner at SF1K on a DGX-2. Naively, it looks like the compilation may silently fail which causes a KeyError on the task at runtime.

```
python benchmark_runner.py --config_file=benchmark_runner/benchmark_config.yaml
Using default arguments
Connected to tcp://172.22.1.26:8786
Pure Dask Queries
28
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/lowering.py", line 30, in from_fndesc
    return cls._memo[fndesc.env_name]
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: '_ZN08NumbaEnv3_2814map_labels$241Ei'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/funcdesc.py", line 93, in lookup_module
    return sys.modules[self.modname]
KeyError: '28'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/utils.py", line 174, in raise_on_meta_error
    yield
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5125, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "queries/q28/tpcx_bb_query_28.py", line 91, in <lambda>
    y = reviews_df["pr_review_rating"].map_partitions(lambda x: x.applymap(map_labels))
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/series.py", line 2578, in applymap
    res_col = self._unaryop(udf)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/frame.py", line 1926, in _unaryop
    return self.__class__._from_table(Frame(data, self._index))
  File "cudf/_lib/table.pyx", line 44, in cudf._lib.table.Table.__init__
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/column_accessor.py", line 38, in __init__
    self._data = OrderedColumnDict(data)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/frame.py", line 1924, in <genexpr>
    data_columns = (col.unary_operator(op) for col in self._columns)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 68, in unary_operator
    return _numeric_column_unaryop(self, op=unaryop)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 449, in _numeric_column_unaryop
    return libcudf.transform.transform(operand, op)
  File "cudf/_lib/transform.pyx", line 80, in cudf._lib.transform.transform
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/utils/cudautils.py", line 311, in compile_udf
    compiled = decorated_udf.compile(type_signature)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/cuda/compiler.py", line 165, in compile
    inline=self.inline)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/cuda/compiler.py", line 44, in compile_cuda
    locals={})
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 603, in compile_extra
    return pipeline.compile_extra(func)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/typed_passes.py", line 369, in run_pass
    metadata=metadata)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/lowering.py", line 80, in __init__
    self.env = Environment.from_fndesc(self.fndesc)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/lowering.py", line 32, in from_fndesc
    inst = cls(fndesc.lookup_globals())
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/funcdesc.py", line 81, in lookup_globals
    return self.global_dict or self.lookup_module().__dict__
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/funcdesc.py", line 96, in lookup_module
    f"can't compile {self.qualname}: "
ModuleNotFoundError: can't compile map_labels: import of module 28 failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/nicholasb/prod/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/tmp/nicholasb/prod/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q28/tpcx_bb_query_28.py", line 346, in main
    client=client, train_data=train_data, test_data=test_data
  File "queries/q28/tpcx_bb_query_28.py", line 285, in post_etl_processing
    y_train = build_labels(train_data)
  File "queries/q28/tpcx_bb_query_28.py", line 91, in build_labels
    y = reviews_df["pr_review_rating"].map_partitions(lambda x: x.applymap(map_labels))
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 642, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5175, in map_partitions
    meta = _emulate(func, *args, udf=True, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5125, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/utils.py", line 195, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `lambda`.

You have supplied a custom function and Dask is unable to
determine the type of output that that function returns.

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ModuleNotFoundError("Failed in nopython mode pipeline (step: nopython mode backend)\ncan't compile map_labels: import of module 28 failed")

Traceback:
---------
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/utils.py", line 174, in raise_on_meta_error
    yield
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/dask/dataframe/core.py", line 5125, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "queries/q28/tpcx_bb_query_28.py", line 91, in <lambda>
    y = reviews_df["pr_review_rating"].map_partitions(lambda x: x.applymap(map_labels))
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/series.py", line 2578, in applymap
    res_col = self._unaryop(udf)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/frame.py", line 1926, in _unaryop
    return self.__class__._from_table(Frame(data, self._index))
  File "cudf/_lib/table.pyx", line 44, in cudf._lib.table.Table.__init__
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/column_accessor.py", line 38, in __init__
    self._data = OrderedColumnDict(data)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/frame.py", line 1924, in <genexpr>
    data_columns = (col.unary_operator(op) for col in self._columns)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 68, in unary_operator
    return _numeric_column_unaryop(self, op=unaryop)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 449, in _numeric_column_unaryop
    return libcudf.transform.transform(operand, op)
  File "cudf/_lib/transform.pyx", line 80, in cudf._lib.transform.transform
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/cudf/utils/cudautils.py", line 311, in compile_udf
    compiled = decorated_udf.compile(type_signature)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/cuda/compiler.py", line 165, in compile
    inline=self.inline)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/cuda/compiler.py", line 44, in compile_cuda
    locals={})
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 603, in compile_extra
    return pipeline.compile_extra(func)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/typed_passes.py", line 369, in run_pass
    metadata=metadata)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/lowering.py", line 80, in __init__
    self.env = Environment.from_fndesc(self.fndesc)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/lowering.py", line 32, in from_fndesc
    inst = cls(fndesc.lookup_globals())
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/funcdesc.py", line 81, in lookup_globals
    return self.global_dict or self.lookup_module().__dict__
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20200727/lib/python3.7/site-packages/numba/core/funcdesc.py", line 96, in lookup_module
    f"can't compile {self.qualname}: "
```

**Comment by beckernick** [comment]
I suspect this might be related to the JIT compiled function's bytecote not being visible during the query loading/compilation process in the benchmark runner

**Comment by VibhuJawa** [comment]
@beckernick , I think this might be good to close now? Can you confirm.

**Comment by beckernick** [comment]
Not yet, we'll need to refactor either q28, how the runner loads the primary query functions, or special case q28's loading

**Comment by VibhuJawa** [comment]
> Not yet, we'll need to refactor either q28, how the runner loads the primary query functions or special case q28's loading

Agreed.   The other options are:

1. Check if moving the function to an `importable` utility helps. 
2. Get rid of `map_labels` altogether (it should be more performant in all probability to do so via cudf boolean operations ) 

I will likely take this on with https://github.com/rapidsai/tpcx-bb/issues/50.

**Comment by beckernick** [comment]
Discussed offline. The above sounds great 👍
