### ISSUE TITLE
[Q02]  TPCX-BB Dask Failures probably due to  column selection failure in read_parquet for df with nulls

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/tpcx-bb#93]
Query 2 Fail Trace

```python
Traceback (most recent call last):
  File "/home/vjawa/tpcx-bb-2/tpcx_bb/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/home/vjawa/tpcx-bb-2/tpcx_bb/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q02/tpcx_bb_query_02.py", line 143, in main
    result_df = result_df.head(q02_limit)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask/dataframe/core.py", line 1006, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask/dataframe/core.py", line 1039, in _head
    result = result.compute()
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/distributed/client.py", line 2693, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/distributed/client.py", line 1990, in gather
    asynchronous=asynchronous,
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/distributed/client.py", line 1849, in _gather
    raise exception.with_traceback(traceback)
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in read_parquet_part
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in <listcomp>
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/dask_cudf/io/parquet.py", line 57, in read_partition
    **kwargs.get("read", {}),
  File "/home/vjawa/conda/envs/rapids-tpcx-bb-aug-19/lib/python3.7/site-packages/cudf/io/parquet.py", line 214, in read_parquet
    use_pandas_metadata=use_pandas_metadata,
  File "cudf/_lib/parquet.pyx", line 151, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/parquet.pyx", line 201, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/table.pyx", line 115, in cudf._lib.table.Table.from_unique_ptr
  File "cudf/_lib/column.pyx", line 411, in cudf._lib.column.Column.from_unique_ptr
RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1597882732206/work/cpp/src/column/column_view.cpp:56: Invalid null mask for non-zero null count.
```

Related CUDF issue: https://github.com/rapidsai/cudf/issues/6048

**Comment by vuule** [comment]
Do you have any regression info, when did you start seeing this issue?

**Comment by VibhuJawa** [comment]
> Do you have any regression info, when did you start seeing this issue?

Not really.  The last sweep we have on file is on `0.15.0a200723` for 10k.  (the issue is not manifested on 1k) 

Maybe @randerzander / @beckernick  / @ayushdg  , Have more recent sweeps that they can share.
