### ISSUE TITLE
[BUG] Dask Q02 fails multi-node SF10K with out of memory error

### ISSUE THREAD

**Issue by beckernick** [rapidsai/tpcx-bb#97]
Using UCX NVLink, Dask Q02 fails on 17 nodes with an out of memory error while reading data in the pre-repartition-task in today's nightlies (2020-08-25).

```
python benchmark_runner.py --config_file=benchmark_runner/benchmark_config.yaml
Using default arguments
Connected to ucx://172.16.8.158:8786
Pure Dask Queries
02
/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask_cudf/core.py:329: UserWarning: Rearranging data by column hash. Divisions will lost. Set ignore_index=False to preserve Index values.
  "Rearranging data by column hash. Divisions will lost. "
Encountered Exception while running query
Traceback (most recent call last):
  File "/home/nicholasb/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/home/nicholasb/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q02/tpcx_bb_query_02.py", line 143, in main
    result_df = result_df.head(q02_limit)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask/dataframe/core.py", line 1006, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask/dataframe/core.py", line 1039, in _head
    result = result.compute()
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/distributed/client.py", line 2713, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/distributed/client.py", line 835, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in read_parquet_part
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in <listcomp>
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/dask_cudf/io/parquet.py", line 57, in read_partition
    **kwargs.get("read", {}),
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20200825/lib/python3.7/site-packages/cudf/io/parquet.py", line 214, in read_parquet
    use_pandas_metadata=use_pandas_metadata,
  File "cudf/_lib/parquet.pyx", line 151, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/parquet.pyx", line 186, in cudf._lib.parquet.read_parquet
MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorMemoryAllocation out of memory
```

```
CUDA 10.2
conda list | grep "blazing\|cudf\|rapids\|dask\|distributed"
# packages in environment at /home/nicholasb/conda/envs/rapids-tpcxbb-20200825:
blazingsql                0.15.0a         cuda10.2_py37_612    blazingsql-nightly/label/cuda10.2
cudf                      0.15.0a200825   cuda_10.2_py37_g4b6b7c0fd_4964    rapidsai-nightly
cuml                      0.15.0a200825   cuda10.2_py37_g27a757c92_2144    rapidsai-nightly
dask                      2.24.0+2.g7d4d9b97          pypi_0    pypi
dask-cuda                 0.15.0a200825          py37_148    rapidsai-nightly
dask-cudf                 0.15.0a200825   py37_g4b6b7c0fd_4964    rapidsai-nightly
distributed               2.24.0+9.ga848ee0c          pypi_0    pypi
faiss-proc                1.0.0                      cuda    rapidsai-nightly
libcudf                   0.15.0a200825   cuda10.2_g4b6b7c0fd_4964    rapidsai-nightly
libcuml                   0.15.0a200825   cuda10.2_g27a757c92_2144    rapidsai-nightly
libcumlprims              0.15.0a200825       cuda10.2_61    rapidsai-nightly
librmm                    0.15.0a200825   cuda10.2_gecdcd0b_725    rapidsai-nightly
rmm                       0.15.0a200825   cuda_10.2_py37_gecdcd0b_725    rapidsai-nightly
ucx                       1.8.1+g6b29558       cuda10.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.15.0a200825+g6b29558        py37_214    rapidsai-nightly
```

**Comment by beckernick** [comment]
Resolved. Just cluster strangeness. This consistently works at 10K. Closing
